[package]
name = "gdr-common"
edition.workspace = true
version.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["io-util", "macros", "rt"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
